apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: go-simple-webserver
  labels:
    app: go-simple-webserver
spec:
  replicas: 10
  strategy:
    canary:
      steps:
        - setWeight: 25
        - pause: { duration: 60s }
        - setWeight: 50
        - pause: { duration: 60s }
        - setWeight: 100
  selector:
    matchLabels:
      app: go-simple-webserver
  template:
    metadata:
      labels:
        app: go-simple-webserver
    spec:
      containers:
        - name: webserver
          image: ghcr.io/sergiu121/ci_cd_lab:cad95ef7d502abfd5a10a2a2af9cc485014944b3e1f2c91dde2c59cf46e648f1
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
